[package]
name = "mitre-attack-simulation-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5", features = ["derive"] }
lazy_static = "1.4"
parking_lot = "0.12"
